baseURL = "https://kyohsuke.github.io/"
DefaultContentLanguage = "ja"
title = "@kyohsuke"
theme = "npq-hugo"
copyright = 'Copyright © 2020 Kyohsuke | Powered by Hugo using the npq hugo theme.'
googleAnalytics = 'UA-846035-3'
pygmentsUseClasses = true
disableKinds = ["term", "taxonomy", "taxonomyTerm"]
hasCJKLanguage = true
disqusShortname = "kyohsuke"
enableRobotsTXT = true

[outputs]
  home = ['HTML']

[params]
  useAvatar = true
  author = "@kyohsuke"
  displayHomeContent = true
  recentMax = 4
  mainSections = ['tools']
  displayMicroBlog = true
  MicroBlogSection = 'misc_notes'

[menu]
  [[menu.main]]
    name = 'トップ'
    url = '/'
    pre = '<i class="fas fa-home fa-ms"></i>'
    weight = 10
  [[menu.main]]
    name = '雑記'
    pre = '<i class="fas fa-book fa-ms"></i>'
    url = '/misc_notes/'
    weight = 15
  [[menu.main]]
    name = 'ツール'
    pre = '<i class="fas fa-tools fa-ms"></i>'
    url = '/tools/'
    weight = 20
  [[menu.main]]
    name = 'twitter'
    url = 'https://twitter.com/i/user/1022113389248737283'
    pre = '<i class="fab fa-twitter fa-ms"></i>'
    weight = 40
  [[menu.main]]
    name = 'Steam'
    url = 'https://steamcommunity.com/id/kyohsuke'
    pre = '<i class="fab fa-steam fa-ms"></i>'
    weight = 50
  [[menu.main]]
    name = 'github'
    url = 'https://github.com/kyohsuke'
    pre = '<i class="fab fa-github fa-ms"></i>'
    weight = 60
  [[menu.main]]
    name = '欲しいもの'
    url = 'http://amzn.to/2MLEYXX'
    pre = '<i class="fab fa-amazon fa-ms"></i>'
    weight = 70



