baseURL = "https://kyohsuke.github.io/"
DefaultContentLanguage = "ja"
title = "@kyohsuke"
theme = "npq-hugo"
copyright = 'Copyright © 2020, Kyohsuke and the Hugo Authors; all rights reserved.'
googleAnalytics = 'UA-846035-3'
pygmentsUseClasses = true
disableKinds = ["taxonomy", "term", "RSS"]
hasCJKLanguage = true

[params]
  useAvatar = true
  author = "@kyohsuke"
  displayHomeContent = true
  recentMax = 4
  mainSections = ['tools']

[menu]
  [[menu.main]]
    name = 'トップ'
    url = '/'
    pre = '<i class="fas fa-home fa-ms"></i>'
    weight = 1
  [[menu.main]]
    name = 'ツール'
    pre = '<i class="fas fa-tools fa-ms"></i>'
    url = '/tools/'
    weight = 2
  [[menu.main]]
    name = 'note'
    url = 'https://note.com/kyohsuke'
    pre = '<i class="far fa-sticky-note fa-rotate-180 fa-ms"></i>&ensp;'
    weight = 3
  [[menu.main]]
    name = 'twitter'
    url = 'https://twitter.com/kyohsuke14'
    pre = '<i class="fab fa-twitter fa-ms"></i>'
    weight = 4
  [[menu.main]]
    name = 'discord'
    url = 'https://discord.com/channels/@me/157617232136896514'
    pre = '<i class="fab fa-discord fa-ms"></i>'
    weight = 5
  [[menu.main]]
    name = 'github'
    url = 'https://github.com/kyohsuke'
    pre = '<i class="fab fa-github fa-ms"></i>'
    weight = 6
