baseURL = "https://kyohsuke.github.io/"
languageCode = "ja-jp"
title = "@kyohsuke"
theme = "npq-hugo"
copyright = 'Copyright © 2008 - 2020, Steve Francia and the Hugo Authors; all rights reserved.'
googleAnalytics = 'UA-846035-3'
pygmentsUseClasses = true

[params]
  useAvatar = true
  author = "@kyohsuke"
  displayHomeContent = true
  recentMax = 4

[menu]
  [[menu.main]]
    name = 'トップ'
    url = '/'
    pre = '<i class="fas fa-home fa-sm"></i>'
    weight = 1
  # [[menu.main]]
  #   name = 'コンテンツ一覧'
  #   pre = '<i class="fas fa-keyboard fa-ms"></i>'
  #   url = '/posts/'
  #   weight = 2
  [[menu.main]]
    name = 'note'
    url = 'https://note.com/kyohsuke'
    pre = '<i class="far fa-sticky-note fa-rotate-180"></i>'
    weight = 3
  [[menu.main]]
    name = 'twitter'
    url = 'https://twitter.com/intent/user?user_id=1022113389248737283'
    pre = '<i class="fab fa-twitter fa-ms"></i>'
    weight = 4
  [[menu.main]]
    name = 'discord'
    url = 'https://github.com/kyohsuke'
    pre = '<i class="fab fa-discord fa-ms"></i>'
    weight = 5
  [[menu.main]]
    name = 'github'
    url = 'https://github.com/kyohsuke'
    pre = '<i class="fab fa-github fa-ms"></i>'
    weight = 6
