name: github pages

on:
  push:
    branches:
      - source
env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_CHANNEL: buildlogs

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master

      - name: Ping Sitemap
        run: |
          curl --silent https://kyohsuke.github.io/sitemap.xml -o before.xml
          if diff -q public/sitemap.xml before.xml; then
            echo "no sitemap changes."
          else
            echo "sitemap changeed. ping!"
            curl --silent https://www.google.com/ping?sitemap=https://kyohsuke.github.io/sitemap.xml -o - > /dev/null
          fi

          curl --silent https://kyohsuke.github.io/misc_notes/index.xml -o notes_before.xml
          if diff -q public/misc_notes/index.xml notes_before.xml; then
            echo "no RSS changes."
          else
            echo "RSS changeed. ping!"
            curl --silent https://www.google.com/ping?sitemap=https://kyohsuke.github.io/misc_notes/index.xml -o - > /dev/null
          fi
      - name: Slack Notification on Success
        if: success()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_TITLE: Test Success
          SLACK_COLOR: good

      - name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2.0.2
        if: failure()
        env:
          SLACK_TITLE: Test Failure
          SLACK_COLOR: danger
